using lena.Domains.Enums;
namespace lena.Domains.Enums
{
  public enum PlanningWorkSpaceSortType
  {
    OrderItemOrderId,
    OrderItemCode,
    OrderItemCustomerName,
    OrderItemCustomerCode,
    OrderItemStuffCode,
    OrderItemStuffName,
    OrderItemStuffNoun,
    OrderItemQty,
    OrderItemUnitName,
    OrderItemStatus,
    OrderItemPlannedQty,
    OrderItemBlockedQty,
    OrderItemProducedQty,
    OrderItemPermissionQty,
    OrderItemSendedQty,
    OrderItemNotPostedQty,
    OrderItemRequestDate,
    OrderItemDeliveryDate,
    OrderItemDateTime,
    OrderItemEmployeeFullName,
    OrderItemBillOfMaterialVersion,
    OrderItemOrderer,
    OrderItemOrderTypeName,
    OrderItemHasChange,
    OrderItemIsArchive,
    OrderItemConfirmationConfirmed,
    OrderItemConfirmationDateTime,
    OrderItemCheckOrderItemConfirmed,
    OrderItemCheckOrderItemDateTime,
    OrderItemChangeStatus,
    OrderItemDocumentNumber,
    OrderItemDocumentType,
    OrderItemDescription,
    OrderItemOrderDescription,


    ProductionRequestCode,
    ProductionRequestQty,
    ProductionRequestUnitName,
    ProductionRequestDeadlineDate,
    ProductionRequestDate,
    ProductionRequestStatus,
    ProductionRequestPlannedQty,
    ProductionRequestScheduledQty,
    ProductionRequestProducedQty,
    ProductionRequestDescription,



    ProductionPlanIsActive,
    ProductionPlanIsPublished,
    ProductionPlanQty,
    ProductionPlanUnitName,
    ProductionPlanStatus,
    ProductionPlanEstimatedDate,
    ProductionPlanDescription,

    ProductionScheduleSemiProductStuffCode,
    ProductionScheduleSemiProductStuffName,
    ProductionScheduleCode,
    ProductionScheduleStepName,
    ProductionScheduleLineName,
    ProductionScheduleIsPublished,
    ProductionScheduleStatus,
    ProductionScheduleQty,
    ProductionScheduleUnitName,
    ProductionScheduleProducedQty,
    ProductionScheduleProducedUnitName,
    ProductionScheduleDateTime,
    ProductionScheduleToDateTime
  }
}
